---
sudo: false
language: ruby
cache: bundler

gemfile:
  - Gemfile
  - gemfiles/rails_4.2.10.gemfile
  - gemfiles/rails_5.2.1.gemfile
  - gemfiles/rails_6.0.0.gemfile

rvm:
  - 2.4
  - 2.5
  - 2.6

jobs:
  exclude:
    - rvm: 2.4
      gemfile: gemfiles/rails_6.0.0.gemfile

before_install: gem install bundler -v 2.0.1

script:
	- bundle exec rspec
	- bundle exec rubocop
